name: e_shop
description: Flutter eCommerce App using Firebase Firestore

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  cloud_firestore: ^3.1.7
  firebase_auth: ^3.3.18
  shared_preferences: ^2.0.15
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.16
  firebase_core: ^1.17.0
  flutter_staggered_grid_view: ^0.4.1
  provider: ^6.0.3
  path_provider: ^2.0.10
  image: ^3.2.0
  intl: ^0.17.0
  build_runner_core: ^6.1.10
  json_serializable: ^6.0.0
  flutter_local_notifications: 7.0.0
  firebase_messaging: ^11.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png



